import type { Dict } from './index'

export const en: Dict = {
  langName: 'English',
  nav: {
    how: 'How it works',
    features: 'Features',
    faq: 'FAQ',
    login: 'Log in',
    start: 'Start free',
    dashboard: 'Dashboard',
  },
  hero: {
    badge: 'Telegram bot · QR · live queue',
    title1: 'The fair queue system',
    titleAccent: 'for sale days',
    title2: '',
    sub: 'Clients register in your Telegram bot and get a random 4-letter code with a QR code. On the sale day the QR is scanned; when the deadline passes, the queue starts — only among those who checked in, ordered by bot registration time.',
    ctaPrimary: 'Start for free',
    ctaSecondary: 'How does it work?',
    note: 'No app for clients — just Telegram',
  },
  board: {
    live: 'LIVE',
    calling: 'Now calling',
    desk: 'Desk {n}',
    next: 'Up next',
    ticket: 'Your code',
    scanUntil: 'Scanning until 10:00',
    botChip: 'Telegram bot',
  },
  audience: {
    title: 'Built for',
    items: ['Real-estate sales', 'Car dealers', 'Banks', 'Clinics', 'Education centers', 'Events', 'Public services'],
  },
  how: {
    title: 'How it works',
    sub: 'Four steps — from registration to served. All automatic.',
    steps: [
      {
        title: 'Register in the bot',
        text: 'A client sends /start to your company bot: name, surname, phone. The bot replies with a random 4-letter code and a QR code — never sequential, impossible to guess.',
      },
      {
        title: 'Sale day — QR check-in',
        text: 'At the office the client shows the QR at reception (USB scanner, camera, or typing the code). Check-in stays open until the deadline you set.',
      },
      {
        title: 'Deadline — the queue forms',
        text: 'At the deadline the queue builds itself: only scanned tickets, ordered by bot registration time. Whoever registered first goes first. Latecomers join the end of the day.',
      },
      {
        title: 'Calling and serving',
        text: 'Managers press “Call next” at their desks. The code appears on the big screen and the client gets a Telegram message. A no-show moves to the end of the day once; a second no-show cancels the ticket.',
      },
    ],
  },
  fair: {
    title: 'Order by registration time. Not by who ran faster.',
    sub: 'No overnight lines, no crowd at the door: what matters is who registered first in the bot — not who arrived first in the morning. Unscanned tickets never enter the queue.',
    facts: [
      'A random 4-letter code — 456,976 possible combinations, impossible to predict or buy.',
      'Only scanned tickets enter the final queue — everything else is excluded.',
      "Latecomers aren't turned away: they're moved to the automatic end-of-day group.",
    ],
    phases: ['1 · Bot registration', '2 · Arrival at the office', '3 · Final queue'],
    registered: 'registered',
    arrived: 'arrived',
    notScanned: 'not scanned — out of the queue',
    queuePos: '',
  },
  features: {
    title: 'A complete toolkit for the sale day',
    sub: 'From registration to the big screen — one system, nothing extra.',
    items: [
      {
        title: 'A bot per company',
        text: 'Get a token from BotFather, paste it in settings — the bot goes live instantly. Registration, QR codes, status and call notifications, all under your bot’s name.',
      },
      {
        title: 'QR check-in — 3 ways',
        text: 'USB scanner (works like a keyboard), phone/laptop camera, or typing the 4-letter code. Clear color-coded results: accepted, end-of-day, or error.',
      },
      {
        title: 'Big screen (TV board)',
        text: 'Called codes with client names, desks, countdowns and the next-up list with bot registration times — live. Just open the link in the TV browser. With an optional chime.',
      },
      {
        title: 'Manager panel',
        text: 'Call · Arrived · No-show · Finish — big tablet-friendly buttons, a call timer, other desks at a glance, and the live waiting list.',
      },
      {
        title: 'Roles and security',
        text: 'Owner, manager and scanner roles. Staff passwords are generated by the system and shown exactly once. Every company’s data is strictly isolated.',
      },
      {
        title: 'Built for bursts',
        text: 'Absorbs 2,000+ registrations in minutes, screens update over WebSocket within a second, and connections heal themselves.',
      },
    ],
  },
  launch: {
    title: 'Launch in 5 minutes',
    sub: 'No technical skills needed — everything happens in the browser.',
    steps: [
      { title: 'Create an account', text: 'Sign up with a phone number and password, then create your company.' },
      { title: 'Connect the bot', text: 'Get a token from @BotFather and paste it into settings — the bot starts immediately.' },
      { title: 'Add your team', text: 'Add managers and scanners, set up desks. Passwords are generated automatically.' },
      { title: 'Publish the event', text: 'Set the sale day and the check-in deadline. Share the bot link with clients — done.' },
    ],
    cta: 'Start now',
  },
  faq: {
    title: 'Frequently asked questions',
    items: [
      {
        q: 'Do clients need to install an app?',
        a: 'No. Registration, the QR code and every notification live in Telegram. At the office the QR is scanned at reception — nothing is installed on the client’s phone.',
      },
      {
        q: 'Why are the codes not sequential?',
        a: 'A random 4-letter code reveals nothing about the position and prevents “code trading”. The final order is decided only by bot registration time.',
      },
      {
        q: 'What if a client is late?',
        a: 'Anyone scanned after the deadline joins the end-of-day queue. A no-show at calling moves to the end of the day once; a second no-show cancels the ticket.',
      },
      {
        q: 'What if the internet drops?',
        a: 'Screens and panels reconnect automatically and keep polling as a fallback. The state lives in the database — nothing is lost.',
      },
      {
        q: 'Multiple branches or events?',
        a: 'Create as many events as you need — each with its own date, deadline and screen. The bot itself offers clients the right event to register for.',
      },
    ],
  },
  cta: {
    title: 'Make your next sale day an orderly one',
    sub: 'Sign up, connect the bot and publish your first event today.',
    button: 'Start for free',
    secondary: 'I have an account — log in',
  },
  footer: {
    tagline: 'Online queue system for sale days',
    product: 'Product',
    account: 'Account',
    rights: 'All rights reserved.',
  },
  auth: {
    loginTitle: 'Welcome back',
    loginSub: 'Log in to your account — the queue is waiting',
    registerTitle: 'Create an account',
    registerSub: 'One minute — and your company is on board',
    firstName: 'First name',
    lastName: 'Last name',
    phone: 'Phone number',
    password: 'Password',
    passwordNew: 'Password (at least 6 characters)',
    submitLogin: 'Log in',
    submitLoginBusy: 'Logging in…',
    submitRegister: 'Create account',
    submitRegisterBusy: 'Creating…',
    noAccount: 'No company yet?',
    registerLink: 'Sign up',
    haveAccount: 'Already have an account?',
    loginLink: 'Log in',
    backHome: 'Home',
    panelTitle: 'The whole sale day in one system',
    panelPoints: [
      'Telegram bot registration and QR codes',
      'A fair queue — ordered by registration time',
      'Live TV board and manager panel',
    ],
  },
}
